### ISSUE TITLE
403 googlevideo.com :(

### ISSUE THREAD

**Issue by ramlan442** [thevarunsharma/pump-downloader#2]
Sir, I got a 403 error when downloading directly via redirector.googlevideo.com is there any instructions to solve this?

Here is link

view-source:https://kotakanimeid.com/video/aDlYclo0QmpXc0tDRkxuQUFLZ0Y1Tm9DUUh2TDAyNVcwUGlpVjRoTWVUMk81bFA5UDVvZ2d2NDczby9lUGJBZjhVQzRqenNYQTNQcW45UEx6bi8yUFE9PQ==&amp;dl=yes&title=nontonanimeid.moe-Kingdom-Season-4-Episode-2

By view source, i get directly for download

**Comment by thevarunsharma** [comment]
Open the network inspector tab and paste the link in your browser. Now identify the request which is triggering the download, right click on it and do 'Copy > Copy as cURL'. Paste the copied command in your terminal and replace 'curl' with 'pump'. Hit enter.
If it fails saying invalid flag, then remove the invalid  flags from the command and re-execute. Also, another thing to note is that `pump` only supports `GET` method, so other request methods might fail. If it is still failing try running the actual curl command that you copied above and see if that works.

**Comment by thevarunsharma** [comment]
Since it is a `403: Forbidden` response, most likely your request is missing the relevant headers. Copying as cURL from the network tab might work.

**Comment by ramlan442** [comment]
ok, i try

btw thanks for making this module, it's really cool
